# Generated by Django 2.1.4 on 2018-12-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSystem',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('locale', models.CharField(default='en-us', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NumberSystemConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('synonyms', models.TextField(default='[]', max_length=500)),
                ('value', models.BigIntegerField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numbersystem.NumberSystem')),
            ],
        ),
    ]
